/**
 * ChurchAfrica ChMS - Mock Location Data
 * Sample data for Victory Chapel Ministry locations
 */

import { Location, LocationAssignment, LocationUtilization } from '../types/location';

export const mockLocations: Location[] = [
  // KUBWA CAMPUS (HQ) - Main Locations
  {
    id: 'loc-1',
    organizationId: 'org-vcm',
    branchId: 'branch-kubwa',
    name: 'Main Sanctuary',
    type: 'main_sanctuary',
    status: 'active',
    address: '12 Church Road',
    city: 'Kubwa',
    state: 'FCT',
    country: 'Nigeria',
    postalCode: '900108',
    coordinates: {
      latitude: 9.0765,
      longitude: 7.4921,
    },
    capacity: 1200,
    seatedCapacity: 1000,
    standingCapacity: 200,
    hasAirConditioning: true,
    hasProjector: true,
    hasSoundSystem: true,
    hasParking: true,
    isWheelchairAccessible: true,
    hasSubLocations: false,
    managerId: 'user-1',
    contactPhone: '+234 803 123 4567',
    contactEmail: 'sanctuary@vcm.org',
    averageUtilization: 75,
    lastUsedDate: '2025-11-13T09:00:00Z',
    description: 'Main worship hall with state-of-the-art sound and lighting systems. Fully air-conditioned with ample parking.',
    imageUrl: 'https://images.unsplash.com/photo-1438232992991-995b7058bbb3?w=800',
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2025-11-13T00:00:00Z',
    createdBy: 'user-1',
  },
  {
    id: 'loc-2',
    organizationId: 'org-vcm',
    branchId: 'branch-kubwa',
    name: 'Annex Hall',
    type: 'annex',
    status: 'active',
    address: '12 Church Road',
    city: 'Kubwa',
    state: 'FCT',
    country: 'Nigeria',
    postalCode: '900108',
    capacity: 300,
    seatedCapacity: 250,
    standingCapacity: 50,
    hasAirConditioning: true,
    hasProjector: true,
    hasSoundSystem: true,
    hasParking: false,
    isWheelchairAccessible: true,
    hasSubLocations: false,
    managerId: 'user-2',
    contactPhone: '+234 803 123 4568',
    averageUtilization: 60,
    description: 'Secondary hall perfect for midweek services, prayer meetings, and special events.',
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2025-11-13T00:00:00Z',
    createdBy: 'user-1',
  },
  {
    id: 'loc-3',
    organizationId: 'org-vcm',
    branchId: 'branch-kubwa',
    name: "Children's Building",
    type: 'classroom',
    status: 'active',
    address: '12 Church Road',
    city: 'Kubwa',
    state: 'FCT',
    country: 'Nigeria',
    postalCode: '900108',
    capacity: 200,
    seatedCapacity: 200,
    hasAirConditioning: true,
    hasProjector: true,
    hasSoundSystem: true,
    hasParking: false,
    isWheelchairAccessible: true,
    hasSubLocations: true,
    managerId: 'user-3',
    contactPhone: '+234 803 123 4569',
    averageUtilization: 85,
    description: 'Dedicated building for children\'s ministry with age-appropriate classrooms and play areas.',
    imageUrl: 'https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=800',
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2025-11-13T00:00:00Z',
    createdBy: 'user-1',
  },
  {
    id: 'loc-4',
    organizationId: 'org-vcm',
    branchId: 'branch-kubwa',
    name: 'Nursery (Ages 0-3)',
    type: 'classroom',
    status: 'active',
    parentLocationId: 'loc-3',
    capacity: 30,
    seatedCapacity: 20,
    hasAirConditioning: true,
    hasProjector: false,
    hasSoundSystem: false,
    isWheelchairAccessible: true,
    averageUtilization: 90,
    description: 'Safe, secure nursery for infants and toddlers with trained caregivers.',
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2025-11-13T00:00:00Z',
    createdBy: 'user-1',
  },
  {
    id: 'loc-5',
    organizationId: 'org-vcm',
    branchId: 'branch-kubwa',
    name: "Preschool Class (Ages 4-6)",
    type: 'classroom',
    status: 'active',
    parentLocationId: 'loc-3',
    capacity: 40,
    seatedCapacity: 40,
    hasAirConditioning: true,
    hasProjector: true,
    hasSoundSystem: true,
    isWheelchairAccessible: true,
    averageUtilization: 95,
    description: 'Interactive classroom with multimedia equipment for young children.',
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2025-11-13T00:00:00Z',
    createdBy: 'user-1',
  },
  {
    id: 'loc-6',
    organizationId: 'org-vcm',
    branchId: 'branch-kubwa',
    name: 'Elementary Class (Ages 7-12)',
    type: 'classroom',
    status: 'active',
    parentLocationId: 'loc-3',
    capacity: 60,
    seatedCapacity: 60,
    hasAirConditioning: true,
    hasProjector: true,
    hasSoundSystem: true,
    isWheelchairAccessible: true,
    averageUtilization: 88,
    description: 'Large classroom for elementary-aged children with interactive learning tools.',
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2025-11-13T00:00:00Z',
    createdBy: 'user-1',
  },
  {
    id: 'loc-7',
    organizationId: 'org-vcm',
    branchId: 'branch-kubwa',
    name: 'Youth Centre',
    type: 'conference_room',
    status: 'active',
    address: '12 Church Road',
    city: 'Kubwa',
    state: 'FCT',
    country: 'Nigeria',
    postalCode: '900108',
    capacity: 150,
    seatedCapacity: 120,
    standingCapacity: 30,
    hasAirConditioning: true,
    hasProjector: true,
    hasSoundSystem: true,
    hasParking: false,
    isWheelchairAccessible: true,
    managerId: 'user-4',
    averageUtilization: 70,
    description: 'Modern space designed for youth services, meetings, and social activities.',
    imageUrl: 'https://images.unsplash.com/photo-1517457373958-b7bdd4587205?w=800',
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2025-11-13T00:00:00Z',
    createdBy: 'user-1',
  },
  {
    id: 'loc-8',
    organizationId: 'org-vcm',
    branchId: 'branch-kubwa',
    name: 'Prayer Room',
    type: 'conference_room',
    status: 'active',
    address: '12 Church Road',
    city: 'Kubwa',
    state: 'FCT',
    country: 'Nigeria',
    capacity: 50,
    seatedCapacity: 40,
    hasAirConditioning: true,
    hasProjector: false,
    hasSoundSystem: true,
    isWheelchairAccessible: true,
    averageUtilization: 55,
    description: 'Quiet, intimate space for prayer meetings and small group gatherings.',
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2025-11-13T00:00:00Z',
    createdBy: 'user-1',
  },
  {
    id: 'loc-9',
    organizationId: 'org-vcm',
    branchId: 'branch-kubwa',
    name: 'Outdoor Pavilion',
    type: 'outdoor',
    status: 'active',
    address: '12 Church Road',
    city: 'Kubwa',
    state: 'FCT',
    country: 'Nigeria',
    capacity: 500,
    standingCapacity: 500,
    hasAirConditioning: false,
    hasProjector: false,
    hasSoundSystem: true,
    hasParking: true,
    isWheelchairAccessible: true,
    averageUtilization: 30,
    description: 'Open-air pavilion with covered seating for outdoor services and events.',
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2025-11-13T00:00:00Z',
    createdBy: 'user-1',
  },

  // WUSE 2 CAMPUS - Main Locations
  {
    id: 'loc-10',
    organizationId: 'org-vcm',
    branchId: 'branch-wuse2',
    name: 'Main Worship Centre',
    type: 'main_sanctuary',
    status: 'active',
    address: '45 Liberation Avenue',
    city: 'Wuse 2',
    state: 'FCT',
    country: 'Nigeria',
    postalCode: '900288',
    coordinates: {
      latitude: 9.0579,
      longitude: 7.4951,
    },
    capacity: 600,
    seatedCapacity: 500,
    standingCapacity: 100,
    hasAirConditioning: true,
    hasProjector: true,
    hasSoundSystem: true,
    hasParking: true,
    isWheelchairAccessible: true,
    managerId: 'user-5',
    contactPhone: '+234 803 234 5678',
    averageUtilization: 80,
    description: 'Modern worship centre in the heart of Abuja city centre.',
    imageUrl: 'https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?w=800',
    createdAt: '2024-06-01T00:00:00Z',
    updatedAt: '2025-11-13T00:00:00Z',
    createdBy: 'user-1',
  },
  {
    id: 'loc-11',
    organizationId: 'org-vcm',
    branchId: 'branch-wuse2',
    name: 'Fellowship Hall',
    type: 'annex',
    status: 'active',
    address: '45 Liberation Avenue',
    city: 'Wuse 2',
    state: 'FCT',
    country: 'Nigeria',
    capacity: 150,
    seatedCapacity: 120,
    standingCapacity: 30,
    hasAirConditioning: true,
    hasProjector: true,
    hasSoundSystem: true,
    hasParking: false,
    isWheelchairAccessible: true,
    averageUtilization: 65,
    description: 'Multi-purpose hall for meetings, bible study, and fellowship events.',
    createdAt: '2024-06-01T00:00:00Z',
    updatedAt: '2025-11-13T00:00:00Z',
    createdBy: 'user-1',
  },
  {
    id: 'loc-12',
    organizationId: 'org-vcm',
    branchId: 'branch-wuse2',
    name: 'Administrative Office',
    type: 'office',
    status: 'active',
    address: '45 Liberation Avenue',
    city: 'Wuse 2',
    state: 'FCT',
    country: 'Nigeria',
    capacity: 20,
    seatedCapacity: 20,
    hasAirConditioning: true,
    hasProjector: false,
    hasSoundSystem: false,
    isWheelchairAccessible: true,
    contactEmail: 'wuse2@vcm.org',
    description: 'Administrative offices for church staff and leadership.',
    createdAt: '2024-06-01T00:00:00Z',
    updatedAt: '2025-11-13T00:00:00Z',
    createdBy: 'user-1',
  },
  {
    id: 'loc-13',
    organizationId: 'org-vcm',
    branchId: 'branch-kubwa',
    name: 'Conference Room A',
    type: 'conference_room',
    status: 'under_maintenance',
    address: '12 Church Road',
    city: 'Kubwa',
    state: 'FCT',
    country: 'Nigeria',
    capacity: 25,
    seatedCapacity: 25,
    hasAirConditioning: true,
    hasProjector: true,
    hasSoundSystem: true,
    isWheelchairAccessible: true,
    averageUtilization: 40,
    description: 'Small meeting room for leadership and ministry team meetings.',
    maintenanceSchedule: '2025-11-20',
    notes: 'Scheduled for air conditioning repair and painting.',
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2025-11-13T00:00:00Z',
    createdBy: 'user-1',
  },
];

export const mockLocationAssignments: LocationAssignment[] = [
  // Sunday Morning Service - Main Sanctuary
  {
    id: 'assign-1',
    locationId: 'loc-1',
    entityId: 's1',
    entityType: 'service',
    startDateTime: '2025-11-17T09:00:00Z',
    endDateTime: '2025-11-17T12:00:00Z',
    expectedAttendance: 950,
    setupTime: 60,
    cleanupTime: 30,
    status: 'scheduled',
    notes: 'Full service with communion',
    createdAt: '2025-11-01T00:00:00Z',
  },
  // Children's Service - Children's Building
  {
    id: 'assign-2',
    locationId: 'loc-3',
    entityId: 's7',
    entityType: 'service',
    startDateTime: '2025-11-17T09:30:00Z',
    endDateTime: '2025-11-17T11:00:00Z',
    expectedAttendance: 180,
    status: 'scheduled',
    createdAt: '2025-11-01T00:00:00Z',
  },
  // Midweek Service - Annex Hall
  {
    id: 'assign-3',
    locationId: 'loc-2',
    entityId: 's3',
    entityType: 'service',
    startDateTime: '2025-11-13T18:00:00Z',
    endDateTime: '2025-11-13T20:00:00Z',
    expectedAttendance: 220,
    actualAttendance: 198,
    status: 'completed',
    createdAt: '2025-11-01T00:00:00Z',
  },
  // Youth Service - Youth Centre
  {
    id: 'assign-4',
    locationId: 'loc-7',
    entityId: 's6',
    entityType: 'service',
    startDateTime: '2025-11-16T17:00:00Z',
    endDateTime: '2025-11-16T19:00:00Z',
    expectedAttendance: 120,
    status: 'scheduled',
    createdAt: '2025-11-01T00:00:00Z',
  },
  // Prayer Meeting - Prayer Room
  {
    id: 'assign-5',
    locationId: 'loc-8',
    entityId: 's4',
    entityType: 'service',
    startDateTime: '2025-11-15T06:00:00Z',
    endDateTime: '2025-11-15T07:30:00Z',
    expectedAttendance: 35,
    actualAttendance: 42,
    status: 'completed',
    createdAt: '2025-11-01T00:00:00Z',
  },
];

export const mockLocationUtilization: LocationUtilization[] = [
  {
    locationId: 'loc-1',
    locationName: 'Main Sanctuary',
    period: 'month',
    startDate: '2025-11-01',
    endDate: '2025-11-30',
    totalHoursAvailable: 300,
    totalHoursUsed: 225,
    utilizationRate: 75,
    totalEvents: 18,
    totalAttendance: 16500,
    averageAttendance: 917,
    capacityUtilization: 76.4,
    peakUsageTimes: [
      { dayOfWeek: 'Sunday', timeRange: '09:00-12:00', utilizationRate: 95 },
      { dayOfWeek: 'Wednesday', timeRange: '18:00-20:00', utilizationRate: 65 },
    ],
  },
  {
    locationId: 'loc-2',
    locationName: 'Annex Hall',
    period: 'month',
    startDate: '2025-11-01',
    endDate: '2025-11-30',
    totalHoursAvailable: 300,
    totalHoursUsed: 180,
    utilizationRate: 60,
    totalEvents: 24,
    totalAttendance: 5280,
    averageAttendance: 220,
    capacityUtilization: 73.3,
    peakUsageTimes: [
      { dayOfWeek: 'Wednesday', timeRange: '18:00-20:00', utilizationRate: 85 },
      { dayOfWeek: 'Saturday', timeRange: '10:00-13:00', utilizationRate: 70 },
    ],
  },
  {
    locationId: 'loc-3',
    locationName: "Children's Building",
    period: 'month',
    startDate: '2025-11-01',
    endDate: '2025-11-30',
    totalHoursAvailable: 240,
    totalHoursUsed: 204,
    utilizationRate: 85,
    totalEvents: 16,
    totalAttendance: 2880,
    averageAttendance: 180,
    capacityUtilization: 90,
    peakUsageTimes: [
      { dayOfWeek: 'Sunday', timeRange: '09:00-12:00', utilizationRate: 98 },
    ],
  },
];
