/**
 * ChurchAfrica ChMS - Mock Data
 * Sample data for development and testing
 */

import { Member } from '../types/member';
import { Service, AttendanceRecord, ServiceType } from '../types/attendance';
import { Event, EventType, EventStatus, RegistrationStatus } from '../types/event';

export const mockMembers: Member[] = [
  {
    id: '1',
    firstName: 'Adewale',
    lastName: 'Okonkwo',
    photo: '',
    dateOfBirth: '1985-03-15',
    gender: 'male',
    contact: {
      phone: '+234 803 456 7890',
      email: 'adewale.okonkwo@email.com',
      address: {
        street: '123 Lagos Street',
        city: 'Lagos',
        state: 'Lagos',
        country: 'Nigeria',
      },
    },
    membershipNumber: 'CA-2020-001',
    membershipType: 'regular',
    status: 'active',
    joinDate: '2020-01-15',
    baptismDate: '2020-03-01',
    salvationDate: '2019-12-25',
    maritalStatus: 'married',
    occupation: 'Software Engineer',
    employer: 'Tech Company Ltd',
    ministries: [
      {
        id: 'm1',
        name: 'Media Ministry',
        role: 'Team Lead',
        startDate: '2020-06-01',
        isActive: true,
      },
    ],
    groups: [
      {
        id: 'g1',
        name: 'Men Fellowship',
        type: 'fellowship',
        joinedDate: '2020-02-01',
      },
    ],
    skills: ['Video Editing', 'Sound Engineering'],
    interests: ['Technology', 'Music'],
    lastAttendance: '2024-10-20',
    attendanceCount: 180,
    attendancePercentage: 92,
    lastDonation: '2024-10-20',
    totalDonations: 450000,
    notes: 'Active in media ministry, excellent technical skills',
    tags: ['media', 'tech'],
    createdAt: '2020-01-15T10:00:00Z',
    updatedAt: '2024-10-20T15:30:00Z',
  },
  {
    id: '2',
    firstName: 'Chioma',
    lastName: 'Nwosu',
    photo: '',
    dateOfBirth: '1992-07-22',
    gender: 'female',
    contact: {
      phone: '+234 805 123 4567',
      email: 'chioma.nwosu@email.com',
      whatsapp: '+234 805 123 4567',
      address: {
        city: 'Abuja',
        state: 'FCT',
        country: 'Nigeria',
      },
    },
    membershipNumber: 'CA-2021-045',
    membershipType: 'regular',
    status: 'active',
    joinDate: '2021-03-10',
    baptismDate: '2021-05-02',
    maritalStatus: 'single',
    occupation: 'Teacher',
    employer: 'Community School',
    ministries: [
      {
        id: 'm2',
        name: 'Children Ministry',
        role: 'Teacher',
        startDate: '2021-04-01',
        isActive: true,
      },
    ],
    groups: [
      {
        id: 'g2',
        name: 'Women Fellowship',
        type: 'fellowship',
        joinedDate: '2021-03-15',
      },
      {
        id: 'g3',
        name: 'Choir',
        type: 'ministry',
        role: 'Alto',
        joinedDate: '2021-06-01',
      },
    ],
    skills: ['Teaching', 'Singing'],
    interests: ['Children Education', 'Music'],
    lastAttendance: '2024-10-20',
    attendanceCount: 145,
    attendancePercentage: 88,
    lastDonation: '2024-10-13',
    totalDonations: 180000,
    tags: ['children', 'music'],
    createdAt: '2021-03-10T09:00:00Z',
    updatedAt: '2024-10-20T16:00:00Z',
  },
  {
    id: '3',
    firstName: 'Emeka',
    lastName: 'Adeyemi',
    photo: '',
    dateOfBirth: '2006-11-05',
    gender: 'male',
    contact: {
      phone: '+234 807 987 6543',
      email: 'emeka.adeyemi@email.com',
      address: {
        city: 'Port Harcourt',
        state: 'Rivers',
        country: 'Nigeria',
      },
    },
    membershipNumber: 'CA-2023-089',
    membershipType: 'regular',
    status: 'active',
    joinDate: '2023-01-08',
    maritalStatus: 'single',
    occupation: 'Student',
    groups: [
      {
        id: 'g4',
        name: 'Youth Fellowship',
        type: 'fellowship',
        joinedDate: '2023-01-15',
      },
    ],
    skills: ['Sports', 'Drama'],
    interests: ['Basketball', 'Acting'],
    lastAttendance: '2024-10-20',
    attendanceCount: 75,
    attendancePercentage: 85,
    tags: ['youth', 'sports'],
    createdAt: '2023-01-08T11:00:00Z',
    updatedAt: '2024-10-20T14:00:00Z',
  },
  {
    id: '4',
    firstName: 'Blessing',
    lastName: 'Okoro',
    photo: '',
    dateOfBirth: '1978-04-12',
    gender: 'female',
    contact: {
      phone: '+234 809 345 6789',
      email: 'blessing.okoro@email.com',
      address: {
        city: 'Enugu',
        state: 'Enugu',
        country: 'Nigeria',
      },
    },
    membershipNumber: 'CA-2018-012',
    membershipType: 'founding',
    status: 'active',
    joinDate: '2018-06-01',
    baptismDate: '2018-08-05',
    salvationDate: '2017-11-20',
    maritalStatus: 'married',
    occupation: 'Business Owner',
    employer: 'Self-Employed',
    family: [
      {
        id: 'f1',
        name: 'Michael Okoro',
        relationship: 'spouse',
      },
      {
        id: 'f2',
        name: 'Grace Okoro',
        relationship: 'child',
      },
    ],
    ministries: [
      {
        id: 'm3',
        name: 'Hospitality Ministry',
        role: 'Coordinator',
        startDate: '2019-01-01',
        isActive: true,
      },
      {
        id: 'm4',
        name: 'Welfare Ministry',
        role: 'Member',
        startDate: '2020-03-01',
        isActive: true,
      },
    ],
    groups: [
      {
        id: 'g2',
        name: 'Women Fellowship',
        type: 'fellowship',
        role: 'Leader',
        joinedDate: '2018-07-01',
      },
    ],
    skills: ['Event Planning', 'Catering'],
    interests: ['Hospitality', 'Community Service'],
    lastAttendance: '2024-10-20',
    attendanceCount: 280,
    attendancePercentage: 95,
    lastDonation: '2024-10-20',
    totalDonations: 850000,
    notes: 'Founding member, very committed to church growth',
    tags: ['founding', 'hospitality', 'leader'],
    createdAt: '2018-06-01T10:00:00Z',
    updatedAt: '2024-10-20T17:00:00Z',
  },
  {
    id: '5',
    firstName: 'Tunde',
    lastName: 'Ibrahim',
    photo: '',
    dateOfBirth: '1990-09-30',
    gender: 'male',
    contact: {
      phone: '+234 802 111 2222',
      email: 'tunde.ibrahim@email.com',
      address: {
        city: 'Ibadan',
        state: 'Oyo',
        country: 'Nigeria',
      },
    },
    membershipNumber: 'CA-2022-067',
    membershipType: 'regular',
    status: 'active',
    joinDate: '2022-05-15',
    baptismDate: '2022-07-10',
    salvationDate: '2022-04-03',
    maritalStatus: 'single',
    occupation: 'Accountant',
    employer: 'Financial Services Ltd',
    ministries: [
      {
        id: 'm5',
        name: 'Finance Ministry',
        role: 'Assistant Treasurer',
        startDate: '2022-09-01',
        isActive: true,
      },
    ],
    groups: [
      {
        id: 'g1',
        name: 'Men Fellowship',
        type: 'fellowship',
        joinedDate: '2022-06-01',
      },
    ],
    skills: ['Accounting', 'Financial Planning'],
    interests: ['Finance', 'Reading'],
    lastAttendance: '2024-10-20',
    attendanceCount: 98,
    attendancePercentage: 90,
    lastDonation: '2024-10-06',
    totalDonations: 320000,
    tags: ['finance'],
    createdAt: '2022-05-15T12:00:00Z',
    updatedAt: '2024-10-20T13:00:00Z',
  },
  {
    id: '6',
    firstName: 'Ngozi',
    lastName: 'Eze',
    photo: '',
    dateOfBirth: '1995-12-18',
    gender: 'female',
    contact: {
      phone: '+234 806 888 9999',
      email: 'ngozi.eze@email.com',
      whatsapp: '+234 806 888 9999',
      address: {
        city: 'Calabar',
        state: 'Cross River',
        country: 'Nigeria',
      },
    },
    membershipNumber: 'CA-2024-105',
    membershipType: 'regular',
    status: 'visitor',
    joinDate: '2024-09-01',
    maritalStatus: 'single',
    occupation: 'Nurse',
    employer: 'General Hospital',
    lastAttendance: '2024-10-13',
    attendanceCount: 6,
    attendancePercentage: 75,
    tags: ['new', 'healthcare'],
    createdAt: '2024-09-01T10:00:00Z',
    updatedAt: '2024-10-13T16:00:00Z',
  },
  {
    id: '7',
    firstName: 'Oluwaseun',
    lastName: 'Balogun',
    photo: '',
    dateOfBirth: '1988-02-28',
    gender: 'male',
    contact: {
      phone: '+234 808 555 6666',
      email: 'seun.balogun@email.com',
      address: {
        city: 'Ilorin',
        state: 'Kwara',
        country: 'Nigeria',
      },
    },
    membershipNumber: 'CA-2019-034',
    membershipType: 'regular',
    status: 'inactive',
    joinDate: '2019-08-20',
    baptismDate: '2019-10-13',
    maritalStatus: 'married',
    occupation: 'Entrepreneur',
    ministries: [
      {
        id: 'm6',
        name: 'Ushering Ministry',
        role: 'Member',
        startDate: '2019-11-01',
        endDate: '2023-12-31',
        isActive: false,
      },
    ],
    lastAttendance: '2023-12-24',
    attendanceCount: 165,
    attendancePercentage: 45,
    notes: 'Relocated to another city, marked as inactive',
    tags: ['relocated'],
    createdAt: '2019-08-20T09:00:00Z',
    updatedAt: '2024-01-10T10:00:00Z',
  },
  {
    id: '8',
    firstName: 'Amaka',
    lastName: 'Obi',
    photo: '',
    dateOfBirth: '2008-06-10',
    gender: 'female',
    contact: {
      phone: '+234 810 777 8888',
      address: {
        city: 'Owerri',
        state: 'Imo',
        country: 'Nigeria',
      },
    },
    membershipNumber: 'CA-2022-078',
    membershipType: 'regular',
    status: 'active',
    joinDate: '2022-07-05',
    maritalStatus: 'single',
    occupation: 'Student',
    groups: [
      {
        id: 'g5',
        name: 'Teenage Ministry',
        type: 'fellowship',
        joinedDate: '2022-07-10',
      },
    ],
    skills: ['Singing', 'Dance'],
    interests: ['Music', 'Art'],
    lastAttendance: '2024-10-20',
    attendanceCount: 95,
    attendancePercentage: 87,
    tags: ['youth', 'creative'],
    createdAt: '2022-07-05T11:00:00Z',
    updatedAt: '2024-10-20T15:00:00Z',
  },
  // Family 1: The Adebayo Family
  {
    id: '9',
    firstName: 'Olufemi',
    lastName: 'Adebayo',
    photo: '',
    dateOfBirth: '1982-05-14',
    gender: 'male',
    contact: {
      phone: '+234 803 222 3333',
      email: 'olufemi.adebayo@email.com',
      address: {
        street: '45 Wuse 2 Avenue',
        city: 'Abuja',
        state: 'FCT',
        country: 'Nigeria',
      },
    },
    membershipNumber: 'CA-2019-025',
    membershipType: 'regular',
    status: 'active',
    joinDate: '2019-03-10',
    baptismDate: '2019-05-12',
    salvationDate: '2018-12-25',
    maritalStatus: 'married',
    occupation: 'Civil Engineer',
    employer: 'Federal Capital Development Authority',
    familyId: 'family-001',
    ministries: [
      {
        id: 'm7',
        name: 'Men Fellowship',
        role: 'Secretary',
        startDate: '2019-06-01',
        isActive: true,
      },
    ],
    groups: [
      {
        id: 'g1',
        name: 'Men Fellowship',
        type: 'fellowship',
        joinedDate: '2019-04-01',
      },
    ],
    skills: ['Project Management', 'Construction'],
    interests: ['Engineering', 'Community Development'],
    lastAttendance: '2024-11-10',
    attendanceCount: 245,
    attendancePercentage: 94,
    lastDonation: '2024-11-10',
    totalDonations: 680000,
    notes: 'Family head, very active in church activities',
    tags: ['family', 'men'],
    createdAt: '2019-03-10T10:00:00Z',
    updatedAt: '2024-11-10T15:30:00Z',
  },
  {
    id: '10',
    firstName: 'Funmilayo',
    lastName: 'Adebayo',
    photo: '',
    dateOfBirth: '1985-08-22',
    gender: 'female',
    contact: {
      phone: '+234 803 222 3334',
      email: 'funmilayo.adebayo@email.com',
      whatsapp: '+234 803 222 3334',
      address: {
        street: '45 Wuse 2 Avenue',
        city: 'Abuja',
        state: 'FCT',
        country: 'Nigeria',
      },
    },
    membershipNumber: 'CA-2019-026',
    membershipType: 'regular',
    status: 'active',
    joinDate: '2019-03-10',
    baptismDate: '2019-05-12',
    salvationDate: '2019-01-06',
    maritalStatus: 'married',
    occupation: 'Pharmacist',
    employer: 'National Hospital Abuja',
    familyId: 'family-001',
    ministries: [
      {
        id: 'm8',
        name: 'Children Ministry',
        role: 'Coordinator',
        startDate: '2019-09-01',
        isActive: true,
      },
    ],
    groups: [
      {
        id: 'g2',
        name: 'Women Fellowship',
        type: 'fellowship',
        joinedDate: '2019-04-01',
      },
    ],
    skills: ['Healthcare', 'Child Education'],
    interests: ['Children', 'Health'],
    lastAttendance: '2024-11-10',
    attendanceCount: 250,
    attendancePercentage: 96,
    lastDonation: '2024-11-10',
    totalDonations: 520000,
    notes: 'Active in children ministry, spouse of Olufemi',
    tags: ['family', 'children'],
    createdAt: '2019-03-10T10:00:00Z',
    updatedAt: '2024-11-10T15:30:00Z',
  },
  {
    id: '11',
    firstName: 'Timilehin',
    lastName: 'Adebayo',
    photo: '',
    dateOfBirth: '2010-11-15',
    gender: 'male',
    contact: {
      phone: '+234 803 222 3333',
      address: {
        street: '45 Wuse 2 Avenue',
        city: 'Abuja',
        state: 'FCT',
        country: 'Nigeria',
      },
    },
    membershipNumber: 'CA-2019-027',
    membershipType: 'regular',
    status: 'active',
    joinDate: '2019-03-10',
    maritalStatus: 'single',
    occupation: 'Student',
    familyId: 'family-001',
    groups: [
      {
        id: 'g5',
        name: 'Teenagers Fellowship',
        type: 'fellowship',
        joinedDate: '2022-01-15',
      },
    ],
    skills: ['Music', 'Sports'],
    interests: ['Football', 'Piano'],
    lastAttendance: '2024-11-10',
    attendanceCount: 185,
    attendancePercentage: 88,
    notes: 'Son of Olufemi and Funmilayo',
    tags: ['family', 'youth'],
    createdAt: '2019-03-10T10:00:00Z',
    updatedAt: '2024-11-10T15:30:00Z',
  },
  {
    id: '12',
    firstName: 'Ayomide',
    lastName: 'Adebayo',
    photo: '',
    dateOfBirth: '2015-03-08',
    gender: 'female',
    contact: {
      phone: '+234 803 222 3333',
      address: {
        street: '45 Wuse 2 Avenue',
        city: 'Abuja',
        state: 'FCT',
        country: 'Nigeria',
      },
    },
    membershipNumber: 'CA-2019-028',
    membershipType: 'regular',
    status: 'active',
    joinDate: '2019-03-10',
    maritalStatus: 'single',
    occupation: 'Student',
    familyId: 'family-001',
    groups: [
      {
        id: 'g6',
        name: 'Children Church',
        type: 'fellowship',
        joinedDate: '2019-03-15',
      },
    ],
    skills: ['Art', 'Dancing'],
    interests: ['Drawing', 'Dancing'],
    lastAttendance: '2024-11-10',
    attendanceCount: 195,
    attendancePercentage: 90,
    notes: 'Daughter of Olufemi and Funmilayo',
    tags: ['family', 'children'],
    createdAt: '2019-03-10T10:00:00Z',
    updatedAt: '2024-11-10T15:30:00Z',
  },
  // Family 2: The Okafor Family
  {
    id: '13',
    firstName: 'Chukwuemeka',
    lastName: 'Okafor',
    photo: '',
    dateOfBirth: '1978-09-20',
    gender: 'male',
    contact: {
      phone: '+234 805 444 5555',
      email: 'chukwuemeka.okafor@email.com',
      address: {
        street: '12 Kubwa Road',
        city: 'Abuja',
        state: 'FCT',
        country: 'Nigeria',
      },
    },
    membershipNumber: 'CA-2020-018',
    membershipType: 'regular',
    status: 'active',
    joinDate: '2020-01-20',
    baptismDate: '2020-03-15',
    salvationDate: '2019-11-10',
    maritalStatus: 'married',
    occupation: 'Business Consultant',
    employer: 'Self-Employed',
    familyId: 'family-002',
    ministries: [
      {
        id: 'm9',
        name: 'Evangelism Ministry',
        role: 'Team Member',
        startDate: '2020-06-01',
        isActive: true,
      },
    ],
    groups: [
      {
        id: 'g1',
        name: 'Men Fellowship',
        type: 'fellowship',
        joinedDate: '2020-02-01',
      },
    ],
    skills: ['Business Strategy', 'Public Speaking'],
    interests: ['Entrepreneurship', 'Ministry'],
    lastAttendance: '2024-11-10',
    attendanceCount: 210,
    attendancePercentage: 91,
    lastDonation: '2024-11-10',
    totalDonations: 790000,
    notes: 'Business owner, committed to church growth',
    tags: ['family', 'business'],
    createdAt: '2020-01-20T10:00:00Z',
    updatedAt: '2024-11-10T15:30:00Z',
  },
  {
    id: '14',
    firstName: 'Chiamaka',
    lastName: 'Okafor',
    photo: '',
    dateOfBirth: '1980-12-05',
    gender: 'female',
    contact: {
      phone: '+234 805 444 5556',
      email: 'chiamaka.okafor@email.com',
      whatsapp: '+234 805 444 5556',
      address: {
        street: '12 Kubwa Road',
        city: 'Abuja',
        state: 'FCT',
        country: 'Nigeria',
      },
    },
    membershipNumber: 'CA-2020-019',
    membershipType: 'regular',
    status: 'active',
    joinDate: '2020-01-20',
    baptismDate: '2020-03-15',
    salvationDate: '2019-11-10',
    maritalStatus: 'married',
    occupation: 'Fashion Designer',
    employer: 'Chiamaka Couture',
    familyId: 'family-002',
    ministries: [
      {
        id: 'm10',
        name: 'Choir',
        role: 'Soprano',
        startDate: '2020-04-01',
        isActive: true,
      },
    ],
    groups: [
      {
        id: 'g2',
        name: 'Women Fellowship',
        type: 'fellowship',
        joinedDate: '2020-02-01',
      },
      {
        id: 'g3',
        name: 'Choir',
        type: 'ministry',
        role: 'Soprano',
        joinedDate: '2020-04-01',
      },
    ],
    skills: ['Fashion Design', 'Singing'],
    interests: ['Fashion', 'Music'],
    lastAttendance: '2024-11-10',
    attendanceCount: 215,
    attendancePercentage: 93,
    lastDonation: '2024-11-10',
    totalDonations: 650000,
    notes: 'Creative and talented, spouse of Chukwuemeka',
    tags: ['family', 'creative'],
    createdAt: '2020-01-20T10:00:00Z',
    updatedAt: '2024-11-10T15:30:00Z',
  },
  {
    id: '15',
    firstName: 'Chidera',
    lastName: 'Okafor',
    photo: '',
    dateOfBirth: '2012-07-18',
    gender: 'female',
    contact: {
      phone: '+234 805 444 5555',
      address: {
        street: '12 Kubwa Road',
        city: 'Abuja',
        state: 'FCT',
        country: 'Nigeria',
      },
    },
    membershipNumber: 'CA-2020-020',
    membershipType: 'regular',
    status: 'active',
    joinDate: '2020-01-20',
    maritalStatus: 'single',
    occupation: 'Student',
    familyId: 'family-002',
    groups: [
      {
        id: 'g5',
        name: 'Teenagers Fellowship',
        type: 'fellowship',
        joinedDate: '2023-01-01',
      },
    ],
    skills: ['Reading', 'Writing'],
    interests: ['Books', 'Poetry'],
    lastAttendance: '2024-11-10',
    attendanceCount: 165,
    attendancePercentage: 86,
    notes: 'Daughter of Chukwuemeka and Chiamaka',
    tags: ['family', 'youth'],
    createdAt: '2020-01-20T10:00:00Z',
    updatedAt: '2024-11-10T15:30:00Z',
  },
];

// Mock Services
export const mockServices: Service[] = [
  {
    id: 's1',
    name: 'Sunday 1st Service',
    type: 'sunday_first' as ServiceType,
    date: '2024-10-27',
    startTime: '08:00',
    endTime: '10:00',
    location: 'Main Sanctuary',
    expectedAttendance: 250,
    notes: 'Regular Sunday morning service',
    isActive: true,
    createdAt: '2024-10-20T10:00:00Z',
  },
  {
    id: 's2',
    name: 'Sunday 2nd Service',
    type: 'sunday_second' as ServiceType,
    date: '2024-10-27',
    startTime: '10:30',
    endTime: '12:30',
    location: 'Main Sanctuary',
    expectedAttendance: 180,
    notes: 'Regular Sunday late morning service',
    isActive: true,
    createdAt: '2024-10-20T10:00:00Z',
  },
  {
    id: 's3',
    name: 'Wednesday Bible Study',
    type: 'midweek' as ServiceType,
    date: '2024-10-23',
    startTime: '18:00',
    endTime: '19:30',
    location: 'Fellowship Hall',
    expectedAttendance: 80,
    notes: 'Weekly Bible study and prayer',
    isActive: true,
    createdAt: '2024-10-20T10:00:00Z',
  },
  {
    id: 's4',
    name: 'Sunday Service',
    type: 'sunday_first' as ServiceType,
    date: '2024-10-20',
    startTime: '09:00',
    endTime: '11:00',
    location: 'Main Sanctuary',
    expectedAttendance: 250,
    notes: 'Last Sunday service',
    isActive: false,
    createdAt: '2024-10-13T10:00:00Z',
  },
  {
    id: 's5',
    name: 'Youth Service',
    type: 'youth' as ServiceType,
    date: '2024-10-26',
    startTime: '16:00',
    endTime: '18:00',
    location: 'Youth Center',
    expectedAttendance: 50,
    notes: 'Monthly youth gathering',
    isActive: true,
    createdAt: '2024-10-20T10:00:00Z',
  },
];

// Mock Attendance Records
export const mockAttendanceRecords: AttendanceRecord[] = [
  // Service s1 (Sunday 1st Service - Oct 27) - Sample attendance
  {
    id: 'a1',
    serviceId: 's1',
    memberId: '1',
    status: 'present',
    checkInTime: '2024-10-27T07:55:00Z',
    checkInMethod: 'app',
    memberName: 'Adewale Okonkwo',
    membershipNumber: 'CA-2020-001',
    isFirstTimer: false,
    isGuest: false,
    createdAt: '2024-10-27T07:55:00Z',
    updatedAt: '2024-10-27T07:55:00Z',
  },
  {
    id: 'a2',
    serviceId: 's1',
    memberId: '2',
    status: 'present',
    checkInTime: '2024-10-27T08:05:00Z',
    checkInMethod: 'manual',
    memberName: 'Chioma Nwosu',
    membershipNumber: 'CA-2021-045',
    isFirstTimer: false,
    isGuest: false,
    createdAt: '2024-10-27T08:05:00Z',
    updatedAt: '2024-10-27T08:05:00Z',
  },
  {
    id: 'a3',
    serviceId: 's1',
    memberId: '4',
    status: 'late',
    checkInTime: '2024-10-27T08:20:00Z',
    checkInMethod: 'manual',
    memberName: 'Blessing Okoro',
    membershipNumber: 'CA-2018-012',
    isFirstTimer: false,
    isGuest: false,
    hasChildren: true,
    childrenCount: 2,
    createdAt: '2024-10-27T08:20:00Z',
    updatedAt: '2024-10-27T08:20:00Z',
  },
  {
    id: 'a4',
    serviceId: 's1',
    memberId: '5',
    status: 'present',
    checkInTime: '2024-10-27T07:50:00Z',
    checkInMethod: 'qr_code',
    memberName: 'Tunde Ibrahim',
    membershipNumber: 'CA-2022-067',
    isFirstTimer: false,
    isGuest: false,
    createdAt: '2024-10-27T07:50:00Z',
    updatedAt: '2024-10-27T07:50:00Z',
  },
  
  // Service s4 (Last Sunday - Oct 20) - Historical data
  {
    id: 'a10',
    serviceId: 's4',
    memberId: '1',
    status: 'present',
    checkInTime: '2024-10-20T08:55:00Z',
    checkInMethod: 'manual',
    memberName: 'Adewale Okonkwo',
    membershipNumber: 'CA-2020-001',
    isFirstTimer: false,
    isGuest: false,
    createdAt: '2024-10-20T08:55:00Z',
    updatedAt: '2024-10-20T08:55:00Z',
  },
  {
    id: 'a11',
    serviceId: 's4',
    memberId: '2',
    status: 'present',
    checkInTime: '2024-10-20T09:02:00Z',
    checkInMethod: 'manual',
    memberName: 'Chioma Nwosu',
    membershipNumber: 'CA-2021-045',
    isFirstTimer: false,
    isGuest: false,
    createdAt: '2024-10-20T09:02:00Z',
    updatedAt: '2024-10-20T09:02:00Z',
  },
  {
    id: 'a12',
    serviceId: 's4',
    memberId: '3',
    status: 'present',
    checkInTime: '2024-10-20T09:10:00Z',
    checkInMethod: 'manual',
    memberName: 'Emeka Adeyemi',
    membershipNumber: 'CA-2023-089',
    isFirstTimer: false,
    isGuest: false,
    createdAt: '2024-10-20T09:10:00Z',
    updatedAt: '2024-10-20T09:10:00Z',
  },
  {
    id: 'a13',
    serviceId: 's4',
    memberId: '4',
    status: 'present',
    checkInTime: '2024-10-20T08:58:00Z',
    checkInMethod: 'manual',
    memberName: 'Blessing Okoro',
    membershipNumber: 'CA-2018-012',
    isFirstTimer: false,
    isGuest: false,
    createdAt: '2024-10-20T08:58:00Z',
    updatedAt: '2024-10-20T08:58:00Z',
  },
  {
    id: 'a14',
    serviceId: 's4',
    memberId: '5',
    status: 'present',
    checkInTime: '2024-10-20T09:05:00Z',
    checkInMethod: 'manual',
    memberName: 'Tunde Ibrahim',
    membershipNumber: 'CA-2022-067',
    isFirstTimer: false,
    isGuest: false,
    createdAt: '2024-10-20T09:05:00Z',
    updatedAt: '2024-10-20T09:05:00Z',
  },
  {
    id: 'a15',
    serviceId: 's4',
    memberId: '8',
    status: 'present',
    checkInTime: '2024-10-20T09:08:00Z',
    checkInMethod: 'manual',
    memberName: 'Amaka Obi',
    membershipNumber: 'CA-2022-078',
    isFirstTimer: false,
    isGuest: false,
    createdAt: '2024-10-20T09:08:00Z',
    updatedAt: '2024-10-20T09:08:00Z',
  },
];

// Mock Events
export const mockEvents: Event[] = [
  {
    id: 'e1',
    title: 'Annual Church Conference 2024',
    description: 'Join us for our annual church conference featuring renowned speakers, worship sessions, and interactive workshops on spiritual growth and leadership development.',
    type: 'conference' as EventType,
    status: 'published' as EventStatus,
    startDate: '2024-11-15T09:00:00Z',
    endDate: '2024-11-17T18:00:00Z',
    isAllDay: false,
    timezone: 'Africa/Lagos',
    recurrence: 'none',
    location: {
      type: 'physical',
      venue: 'Main Sanctuary',
      address: '123 Church Avenue, Victoria Island',
      city: 'Lagos',
      state: 'Lagos',
      country: 'Nigeria',
    },
    registration: {
      required: true,
      status: 'open' as RegistrationStatus,
      capacity: 500,
      registeredCount: 342,
      attendedCount: 0,
      waitlistCount: 0,
      deadline: '2024-11-10T23:59:59Z',
      fee: 5000,
      currency: 'NGN',
      requiresApproval: false,
      allowGuestRegistration: true,
      guestLimit: 2,
    },
    organizer: {
      id: '1',
      name: 'Pastor John Mensah',
      email: 'pastor@churchafrica.org',
      phone: '+234 800 123 4567',
      department: 'Leadership',
    },
    tags: ['conference', 'leadership', 'worship'],
    targetAudience: ['all'],
    ministries: ['Leadership', 'Worship'],
    reminders: {
      enabled: true,
      times: [10080, 1440, 60], // 1 week, 1 day, 1 hour
      methods: ['email', 'sms'],
    },
    createdBy: '1',
    createdByName: 'Admin User',
    createdAt: '2024-09-15T10:00:00Z',
    updatedAt: '2024-10-20T15:30:00Z',
    publishedAt: '2024-09-20T12:00:00Z',
  },
  {
    id: 'e2',
    title: 'Youth Empowerment Crusade',
    description: 'A special crusade targeting young people with messages of hope, purpose, and empowerment. Special guest speaker: Rev. David Oyedepo Jr.',
    type: 'crusade' as EventType,
    status: 'published' as EventStatus,
    startDate: '2024-11-02T18:00:00Z',
    endDate: '2024-11-02T21:00:00Z',
    isAllDay: false,
    timezone: 'Africa/Lagos',
    recurrence: 'none',
    location: {
      type: 'hybrid',
      venue: 'Youth Center',
      address: '45 Youth Street, Lekki',
      city: 'Lagos',
      state: 'Lagos',
      country: 'Nigeria',
      onlineLink: 'https://zoom.us/j/123456789',
      onlinePlatform: 'Zoom',
    },
    registration: {
      required: true,
      status: 'open' as RegistrationStatus,
      capacity: 300,
      registeredCount: 187,
      attendedCount: 0,
      waitlistCount: 0,
      requiresApproval: false,
      allowGuestRegistration: true,
      guestLimit: 3,
    },
    organizer: {
      id: '3',
      name: 'Youth Ministry Team',
      email: 'youth@churchafrica.org',
      phone: '+234 801 234 5678',
      department: 'Youth Ministry',
    },
    tags: ['crusade', 'youth', 'empowerment'],
    targetAudience: ['youth'],
    ministries: ['Youth Ministry'],
    reminders: {
      enabled: true,
      times: [1440, 120], // 1 day, 2 hours
      methods: ['email', 'sms', 'push'],
    },
    createdBy: '3',
    createdByName: 'Youth Leader',
    createdAt: '2024-10-01T09:00:00Z',
    updatedAt: '2024-10-18T14:20:00Z',
    publishedAt: '2024-10-05T10:00:00Z',
  },
  {
    id: 'e3',
    title: 'Marriage Retreat Weekend',
    description: 'A transformative weekend retreat for married couples focusing on strengthening relationships, effective communication, and building godly homes.',
    type: 'retreat' as EventType,
    status: 'published' as EventStatus,
    startDate: '2024-11-08T15:00:00Z',
    endDate: '2024-11-10T14:00:00Z',
    isAllDay: false,
    timezone: 'Africa/Lagos',
    recurrence: 'none',
    location: {
      type: 'physical',
      venue: 'Grace Haven Retreat Center',
      address: 'KM 45, Lekki-Epe Expressway',
      city: 'Lekki',
      state: 'Lagos',
      country: 'Nigeria',
    },
    registration: {
      required: true,
      status: 'open' as RegistrationStatus,
      capacity: 50,
      registeredCount: 38,
      attendedCount: 0,
      waitlistCount: 5,
      deadline: '2024-11-01T23:59:59Z',
      fee: 45000,
      currency: 'NGN',
      requiresApproval: true,
      allowGuestRegistration: false,
      customFields: [
        {
          name: 'Anniversary Date',
          type: 'text',
          required: true,
        },
        {
          name: 'Special Dietary Requirements',
          type: 'text',
          required: false,
        },
      ],
    },
    organizer: {
      id: '4',
      name: 'Family Ministry',
      email: 'family@churchafrica.org',
      phone: '+234 802 345 6789',
      department: 'Family Ministry',
    },
    tags: ['retreat', 'marriage', 'couples'],
    targetAudience: ['adults'],
    ministries: ['Family Ministry'],
    reminders: {
      enabled: true,
      times: [10080, 2880, 1440], // 1 week, 2 days, 1 day
      methods: ['email', 'sms'],
    },
    createdBy: '4',
    createdByName: 'Family Coordinator',
    createdAt: '2024-09-10T11:00:00Z',
    updatedAt: '2024-10-22T09:15:00Z',
    publishedAt: '2024-09-15T08:00:00Z',
  },
  {
    id: 'e4',
    title: 'Leadership Training Workshop',
    description: 'Intensive training for current and aspiring ministry leaders. Topics include servant leadership, team building, conflict resolution, and strategic planning.',
    type: 'workshop' as EventType,
    status: 'published' as EventStatus,
    startDate: '2024-10-28T10:00:00Z',
    endDate: '2024-10-28T16:00:00Z',
    isAllDay: false,
    timezone: 'Africa/Lagos',
    recurrence: 'none',
    location: {
      type: 'physical',
      venue: 'Conference Room A',
      address: '123 Church Avenue, Victoria Island',
      city: 'Lagos',
      state: 'Lagos',
      country: 'Nigeria',
    },
    registration: {
      required: true,
      status: 'open' as RegistrationStatus,
      capacity: 80,
      registeredCount: 64,
      attendedCount: 0,
      waitlistCount: 0,
      deadline: '2024-10-26T23:59:59Z',
      requiresApproval: true,
      allowGuestRegistration: false,
    },
    organizer: {
      id: '1',
      name: 'Leadership Development Team',
      email: 'leadership@churchafrica.org',
      phone: '+234 803 456 7890',
      department: 'Leadership',
    },
    tags: ['workshop', 'leadership', 'training'],
    targetAudience: ['members'],
    ministries: ['Leadership', 'All Ministries'],
    reminders: {
      enabled: true,
      times: [2880, 1440, 60], // 2 days, 1 day, 1 hour
      methods: ['email'],
    },
    createdBy: '1',
    createdByName: 'Admin User',
    createdAt: '2024-09-25T10:00:00Z',
    updatedAt: '2024-10-21T16:45:00Z',
    publishedAt: '2024-09-28T09:00:00Z',
  },
  {
    id: 'e5',
    title: 'Online Prayer Meeting',
    description: 'Join us for our weekly online prayer session. A time to seek God together, intercede for our community, and experience corporate worship.',
    type: 'prayer_night' as EventType,
    status: 'published' as EventStatus,
    startDate: '2024-10-30T20:00:00Z',
    endDate: '2024-10-30T21:30:00Z',
    isAllDay: false,
    timezone: 'Africa/Lagos',
    recurrence: 'weekly',
    recurrenceDays: [3], // Wednesday
    location: {
      type: 'online',
      onlineLink: 'https://zoom.us/j/987654321',
      onlinePlatform: 'Zoom',
    },
    registration: {
      required: false,
      status: 'open' as RegistrationStatus,
      registeredCount: 0,
      attendedCount: 0,
      waitlistCount: 0,
      requiresApproval: false,
      allowGuestRegistration: true,
    },
    organizer: {
      id: '2',
      name: 'Prayer Ministry',
      email: 'prayer@churchafrica.org',
      phone: '+234 804 567 8901',
      department: 'Prayer Ministry',
    },
    tags: ['prayer', 'online', 'weekly'],
    targetAudience: ['all'],
    ministries: ['Prayer Ministry'],
    reminders: {
      enabled: true,
      times: [60, 15], // 1 hour, 15 minutes
      methods: ['email', 'push'],
    },
    createdBy: '2',
    createdByName: 'Prayer Coordinator',
    createdAt: '2024-08-01T10:00:00Z',
    updatedAt: '2024-10-23T11:00:00Z',
    publishedAt: '2024-08-05T12:00:00Z',
  },
  {
    id: 'e6',
    title: 'Community Outreach - Orphanage Visit',
    description: 'Join our outreach team as we visit the Hope Children\'s Home. We\'ll be providing food, clothing, educational materials, and spending quality time with the children.',
    type: 'outreach' as EventType,
    status: 'published' as EventStatus,
    startDate: '2024-11-09T09:00:00Z',
    endDate: '2024-11-09T15:00:00Z',
    isAllDay: false,
    timezone: 'Africa/Lagos',
    recurrence: 'none',
    location: {
      type: 'physical',
      venue: 'Hope Children\'s Home',
      address: '78 Charity Road, Surulere',
      city: 'Lagos',
      state: 'Lagos',
      country: 'Nigeria',
    },
    registration: {
      required: true,
      status: 'open' as RegistrationStatus,
      capacity: 40,
      registeredCount: 28,
      attendedCount: 0,
      waitlistCount: 0,
      deadline: '2024-11-06T23:59:59Z',
      requiresApproval: false,
      allowGuestRegistration: true,
      guestLimit: 1,
    },
    organizer: {
      id: '5',
      name: 'Welfare Ministry',
      email: 'welfare@churchafrica.org',
      phone: '+234 805 678 9012',
      department: 'Welfare',
    },
    tags: ['outreach', 'community', 'orphanage'],
    targetAudience: ['all'],
    ministries: ['Welfare Ministry'],
    reminders: {
      enabled: true,
      times: [4320, 1440], // 3 days, 1 day
      methods: ['email', 'sms'],
    },
    createdBy: '5',
    createdByName: 'Welfare Coordinator',
    createdAt: '2024-10-15T09:00:00Z',
    updatedAt: '2024-10-24T10:30:00Z',
    publishedAt: '2024-10-17T11:00:00Z',
  },
  {
    id: 'e7',
    title: 'Children\'s Fun Day',
    description: 'A day of fun-filled activities for children aged 4-12. Games, bouncing castles, face painting, talent shows, and biblical lessons in a fun environment!',
    type: 'children_program' as EventType,
    status: 'published' as EventStatus,
    startDate: '2024-11-23T10:00:00Z',
    endDate: '2024-11-23T16:00:00Z',
    isAllDay: false,
    timezone: 'Africa/Lagos',
    recurrence: 'none',
    location: {
      type: 'physical',
      venue: 'Church Playground',
      address: '123 Church Avenue, Victoria Island',
      city: 'Lagos',
      state: 'Lagos',
      country: 'Nigeria',
    },
    registration: {
      required: true,
      status: 'open' as RegistrationStatus,
      capacity: 200,
      registeredCount: 145,
      attendedCount: 0,
      waitlistCount: 0,
      deadline: '2024-11-20T23:59:59Z',
      fee: 2000,
      currency: 'NGN',
      requiresApproval: false,
      allowGuestRegistration: true,
      guestLimit: 3,
      customFields: [
        {
          name: 'Child Age',
          type: 'text',
          required: true,
        },
        {
          name: 'Allergies/Medical Conditions',
          type: 'text',
          required: false,
        },
      ],
    },
    organizer: {
      id: '2',
      name: 'Children Ministry',
      email: 'children@churchafrica.org',
      phone: '+234 806 789 0123',
      department: 'Children Ministry',
    },
    tags: ['children', 'fun', 'games'],
    targetAudience: ['children'],
    ministries: ['Children Ministry'],
    reminders: {
      enabled: true,
      times: [7200, 1440], // 5 days, 1 day
      methods: ['email', 'sms'],
    },
    createdBy: '2',
    createdByName: 'Children Coordinator',
    createdAt: '2024-10-10T09:00:00Z',
    updatedAt: '2024-10-23T14:00:00Z',
    publishedAt: '2024-10-12T10:00:00Z',
  },
  {
    id: 'e8',
    title: 'Financial Freedom Seminar',
    description: 'Learn biblical principles of financial stewardship, budgeting, investing, and debt management. Guest speaker: Financial expert Pastor Chris Ade.',
    type: 'seminar' as EventType,
    status: 'completed' as EventStatus,
    startDate: '2024-10-19T14:00:00Z',
    endDate: '2024-10-19T17:00:00Z',
    isAllDay: false,
    timezone: 'Africa/Lagos',
    recurrence: 'none',
    location: {
      type: 'physical',
      venue: 'Main Sanctuary',
      address: '123 Church Avenue, Victoria Island',
      city: 'Lagos',
      state: 'Lagos',
      country: 'Nigeria',
    },
    registration: {
      required: true,
      status: 'closed' as RegistrationStatus,
      capacity: 150,
      registeredCount: 150,
      attendedCount: 132,
      waitlistCount: 0,
      deadline: '2024-10-17T23:59:59Z',
      requiresApproval: false,
      allowGuestRegistration: true,
      guestLimit: 1,
    },
    organizer: {
      id: '5',
      name: 'Finance Ministry',
      email: 'finance@churchafrica.org',
      phone: '+234 807 890 1234',
      department: 'Finance',
    },
    tags: ['seminar', 'finance', 'stewardship'],
    targetAudience: ['adults'],
    ministries: ['Finance Ministry'],
    reminders: {
      enabled: true,
      times: [2880, 1440, 60],
      methods: ['email', 'sms'],
    },
    createdBy: '5',
    createdByName: 'Finance Team',
    createdAt: '2024-09-05T10:00:00Z',
    updatedAt: '2024-10-20T09:00:00Z',
    publishedAt: '2024-09-10T12:00:00Z',
  },
];